name: gh-deploy
on: [push]
permissions:
  contents: write
jobs:
  #Build job:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm for use with actions
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Configure Git identity
        run: |
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Clean install dependencies
        run: pnpm install

      - name: Build the project
        run: |
          echo "current_branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          git checkout --orphan gh-pages
          git branch --show-current
          git branch --list
          pnpm build
          git branch --show-current
          git branch --list
      
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: dist

      - name: Clean up
        run: |
          git branch --list
          git rev-parse --abbrev-ref HEAD
          rm -r dist
          git checkout -f "$current_branch"
          git branch -D gh-pages
  
  #Deploy job
  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2