name: gh-deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  gh-page-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm for use with actions
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Configure Git identity
        run: |
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Clean install dependencies
        run: pnpm install

      - name: Run deploy script
        run: bash scripts/gh-pages-deploy.sh